name: goViral

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2

    - name: Install MAFFT
      run: |
        conda install bioconda::mafft

    - name: Run tests with coverage
      run: |
        coverage run -m unittest2 discover tests
        coverage report

    - name: Generate HTML coverage report
      run: coverage html

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: htmlcov/